[server]
enableXsrfProtection = true
enableCORS = false
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = false
